import axios from 'axios'

export const FETCH_PARENTS = 'FETCH_PARENTS';
export const FETCH_PARENTS_SUCCESS ='FETCH_PARENTS_SUCCESS';
export const FETCH_PARENTS_FAIL = 'FETCH_PARENTS_FAIL';
export const FETCH_VOLUNTEERS = 'FETCH_VOLUNTEERS';
export const FETCH_VOLUNTEERS_SUCCESS ='FETCH_VOLUNTEERS_SUCCESS';
export const FETCH_VOLUNTEERS_FAIL = 'FETCH_VOLUNTEERS_FAIL';
export const ADD_POST= 'ADD_POST';
export const ADD_QUESTION= 'ADD_QUESTION';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_QUESTION = 'DELETE_QUESTION';

